apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudfilepvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: cloudfilepv
  resources:
    requests:
      storage: 5Gi