apiVersion: apps/v1
kind: Deployment
metadata:
  name: reader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reader
  template:
    metadata:
      labels:
        app: reader
    spec:
      containers:
      - name: nginx
        image: nginx:stable-alpine
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
        ports:
        - containerPort: 80
        volumeMounts:
        - name: cloudfile
          mountPath: /usr/share/nginx/html
          readOnly: true
      volumes:
      - name: cloudfile
        persistentVolumeClaim:
          claimName: cloudfilepvc