apiVersion: apps/v1
kind: Deployment
metadata:
  name: writer
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: writer
  template:
    metadata:
      labels:
        app: writer
    spec:
      containers:
      - name: content
        image: alpine:latest
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
        volumeMounts:
        - name: cloudfile
          mountPath: /html
        command: ["/bin/sh", "-c"]
        args:
        - while true; do
          echo "$(date), ${HOSTNAME}" >> /html/data.txt;
          echo "Date :$(date), Writer :${HOSTNAME}";
          sleep 10;  
          done
      volumes:
      - name: cloudfile
        persistentVolumeClaim:
          claimName: cloudfilepvc